#!/home/git/ruby
# TODO: relativize Ruby path

# Copyright (C) 2011 Marek Jelen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Libraries
require "socket"
require 'yaml'

# Constants
CONFIG = YAML.load_file('/wc/config/git.yml')
REPOS = CONFIG["paths"]["repositories"]
USER = ENV["GIT_USERNAME"]
SOCKET = UNIXSocket.new(CONFIG["paths"]["socket"])

# One line per ref
$stdin.each_line do |line|
  from, to, ref = line.split(" ")
  ref.sub!("refs/heads/", "")
  repo = File.expand_path(".").sub(REPOS, "")
  socket.write("push|#{USER}|#{to}|#{ref}|#{repo}\n")
end

socket.close
